Configs
fcodelabs/con-dulanga-fortifyasia-cloud pull request #4
Opened 2021-07-01 07:18 UTC by JinapriyaM

- get configs endpoint.

2021-07-02 04:54 UTC, JinapriyaM commented
- get configs endpoint [FA-21]
- fund related querying endpoints [FA-27]
- fund related add/edit endpoints [FA-30]

2021-07-04 13:36 UTC, Ramesh-X requested changes

2021-07-04 13:36 UTC, Ramesh-X commented on apps/legacy/src/funds/dto/query-params.dto.ts
> +  remove = '';
what is this param

2021-07-05 04:32 UTC, Ramesh-X approved these changes

2021-07-05 04:32 UTC, merged